### PR TITLE
Support for Virtualbox 6.1 #210

### PR DESCRIPTION
**Pull request by cesium147**

### CODE REVIEW

**Comment by trasherdk** [comment]
This should go in a `v6.1 branch`, and `develop`  should go in a `v6.0 branch`.

**Comment by JasMich** [comment]
Could you merge? It's working perfectly!

**Comment by chotaire** [comment]
I see WDSL has been updated. People should test if creating snapshots works before considering to merge. This is the reason I refused to update WDSL in previous patches.  @JasMich would you be willing to try creating a snapshot from within phpVirtualBox and see if the snaphot becomes visible? If you even get this far, all other snapshot commands also need to be tested.

**Comment by JasMich** [comment]
No, snapshots do not seem to work.

**Comment by chotaire** [comment]
Well, that's a showstopper as it breaks major functionality. @cesium147 is this something you could look into?

**Comment by unbob** [comment]
This change in vboxconnector.php works, but not entirely sure what it means. See "5.107.82 takeSnapshot", page 245, [SDKRef.pdf](https://download.virtualbox.org/virtualbox/SDKRef.pdf). This should perhaps be the state of paused... although when testing, true or false doesn't seem to make a difference. Maybe something else related to snapshots needs support in phpvirtualbox. I've not used live snapshots with virtualbox before.
```diff
@@ -4706,7 +4706,7 @@ class vboxconnector {
                        $machine->lockMachine($this->session->handle, ((string)$machine->sessionState == 'Unlocked' ? 'Write' : 'Shared'));
 
                        /* @var $progress IProgress */
-                       list($progress, $snapshotId) = $this->session->machine->takeSnapshot($args['name'], $args['description'], null);
+                       list($progress, $snapshotId) = $this->session->machine->takeSnapshot($args['name'], $args['description'], false);
 
                        // Does an exception exist?
                        try {
```

**Comment by cesium147** [comment]
Thanks @unbob, i applied you patch

**Comment by chotaire** [comment]
Fantastic, @cesium147 and @unbob!
Testers, can you check if everything works now?
@h6w would you be so nice to review this PR with priority please?

I will retract two outstanding PRs if this one goes through and would rebase from here.

**Comment by h6w** [comment]
Thanks @cesium147!  Good quality patch.  There's an extraneous newline but I also concur with another patch that CRLF is no longer necessary in modern browsers so we'll filter that out later.  

Also note that my comparison of this wsdl with the one on the VBox website 6.1.2 is that we now have a new network adapter:

```
1842a1843
>             Virtio_1_0: 8 -
1853a1855
>           <xsd:enumeration value="Virtio_1_0"/>
```

The wsdl in this patch therefore must be from a previous 6.1 release.

I won't be doing an official 6.1 release until the heavy reports of issues with the master branch dies down a bit - many of the issues seem to be serious and unclear and I don't want to make things worse.

Sorry for being a bit quiet.  I'm focusing on removing flash at the moment as that's an impending deadline, particularly since Edge just moved to Webkit so we're going to be pretty much a two-tiered web soon - Webkit vs Gecko.

**Pull request merged**
