### PR TITLE
Add selection of graphics controller (VBoxVGS/VMSVGA/VboxSVGA) (by pasha1st)

### PR DESCRIPTION
**Pull request by chotaire**
This pull request adds the ability to select the graphics controller (VBoxVGS/VMSVGA/VboxSVGA).

Coded by @pasha1st - his pull request https://github.com/phpvirtualbox/phpvirtualbox/pull/167 got legitimately rejected due to several issues so I am lending a helping hand and split this into multiple pull requests. This needs tested and finally merged, we need to move forward.

### CODE REVIEW

**Comment by chotaire** [comment]
It appears there are some issues when creating a new VM. This needs a fix before merge.

```
Exception Object
(
    [message:protected] => Attribute does not exist
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /usr/share/nginx/html/endpoints/lib/vboxServiceWrappers.php
    [line:protected] => 204
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /usr/share/nginx/html/endpoints/lib/vboxconnector.php
                    [line] => 3855
                    [function] => __get
                    [class] => VBox_Struct
                    [type] => ->
                    [args] => Array
                        (
                            [0] => recommendedGraphicsController
                        )

                )

            [1] => Array
                (
                    [file] => /usr/share/nginx/html/endpoints/lib/vboxconnector.php
                    [line] => 951
                    [function] => remote_machineCreate
                    [class] => vboxconnector
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [disk] => /home/vbox/VirtualBox VMs/centos8s/centos8s.vdi
                                    [ostype] => RedHat_64
                                    [memory] => 2048
                                    [name] => centos8s
                                )

                        )

                )

            [2] => Array
                (
                    [file] => /usr/share/nginx/html/endpoints/api.php
                    [line] => 316
                    [function] => __call
                    [class] => vboxconnector
                    [type] => ->
                    [args] => Array
                        (
                            [0] => machineCreate
                            [1] => Array
                                (
                                    [0] => Array
                                        (
                                            [disk] => /home/vbox/VirtualBox VMs/centos8s/centos8s.vdi
                                            [ostype] => RedHat_64
                                            [memory] => 2048
                                            [name] => centos8s
                                        )

                                    [1] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [data] => Array
                                                        (
                                                            [responseData] => 
                                                            [success] => 
                                                            [key] => 53474945cfd7ac0bf8114767c209c2a6
                                                        )

                                                    [errors] => Array
                                                        (
                                                        )

                                                    [persist] => Array
                                                        (
                                                        )

                                                    [messages] => Array
                                                        (
                                                        )

                                                )

                                        )

                                )

                        )

                )

            [3] => Array
                (
                    [file] => /usr/share/nginx/html/endpoints/api.php
                    [line] => 316
                    [function] => machineCreate
                    [class] => vboxconnector
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [disk] => /home/vbox/VirtualBox VMs/centos8s/centos8s.vdi
                                    [ostype] => RedHat_64
                                    [memory] => 2048
                                    [name] => centos8s
                                )

                            [1] => Array
                                (
                                    [0] => Array
                                        (
                                            [data] => Array
                                                (
                                                    [responseData] => 
                                                    [success] => 
                                                    [key] => 53474945cfd7ac0bf8114767c209c2a6
                                                )

                                            [errors] => Array
                                                (
                                                )

                                            [persist] => Array
                                                (
                                                )

                                            [messages] => Array
                                                (
                                                )

                                        )

                                )

                        )

                )

        )

    [previous:Exception:private] => 
)

```

**Comment by trasherdk** [comment]
This wont work until `vboxweb.wsdl` get upgraded to 6.0.x
It's currently a hybrid between 5.2 and 6.0

**Comment by cesium147** [comment]
patch to support version 6.1-0 [chot-select-gpu_6.1-0](https://github.com/cesium147/phpvirtualbox/commit/b776989f5558fe9b1f0bdf17109d115f7d7038c4)

**Comment by trasherdk** [comment]
I'll take a look at your fork once I get a 6.1 server running on a test server.
6.1 is a little too young to run on my production server.

**Comment by chotaire** [comment]
> This wont work until `vboxweb.wsdl` get upgraded to 6.0.x
> It's currently a hybrid between 5.2 and 6.0

For good reason, WDSL 6.0 and 6.1 breaks snapshot functionality. This pull request should neither be merged nor ported to 6.1 before snapshot functionality is not fixed when using a recent version of WDSL.

**Comment by trasherdk** [comment]
Snapshot's are working on my 6.0.10 branch :)
image

image

**Comment by chotaire** [comment]
And "your branch" is using WDSL 6.0 with this pull request merged?

**Comment by trasherdk** [comment]
I, currently, do not have a local test server to run version 6.1, and are not able to upgrade the production host.

Version 6.0 is still actively maintained by Oracle, and I'm pretty sure, I'm not alone, in not upgrading to latest version, every time a new version is released.
As soon as I get spare hardware, I will start working on 6.1. Until then I will continue work on 6.0 branch.

**Comment by chotaire** [comment]
So where's the patch? "Your branch" is not relevant here, this is upstream. If you are saying that this feature works on your fork with WDSL 6.0, including creating snapshots, creating VMs and not breaking other features currently in HEAD, then let's not discuss around but -submit- a proper PR.

**Comment by h6w** [comment]
Sorry for the delay in approving this patch.  Excellent work @chotaire :-)

**Comment by chotaire** [comment]
@h6w Thanks but this PR was not ready for merge. This merge breaks phpvirtualbox when simply clicking on a VM, even with @cesium147's patch for VirtualBox 6.1. 

```
Exception Object
(
    [message:protected] => Attribute does not exist
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /usr/share/nginx/html/endpoints/lib/vboxServiceWrappers.php
    [line:protected] => 56
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /usr/share/nginx/html/endpoints/lib/vboxconnector.php
                    [line] => 4227
                    [function] => __get
                    [class] => VBox_ManagedObject
                    [type] => ->
                    [args] => Array
                        (
                            [0] => VRAMSize
                        )

                )

            [1] => Array
                (
                    [file] => /usr/share/nginx/html/endpoints/lib/vboxconnector.php
                    [line] => 3569
                    [function] => _machineGetDetails
                    [class] => vboxconnector
                    [type] => ->
                    [args] => Array
                        (
                            [0] => IMachine Object
                                (
                                    [connection:protected] => SoapClient Object
                                        (
                                            [location] => http://127.0.0.1:18083/
                                            [_features] => 5
                                            [_connection_timeout] => 20
                                            [_soap_version] => 1
                                            [sdl] => Resource id #12
                                            [httpsocket] => Resource id #13
                                            [_use_proxy] => 0
                                            [httpurl] => Resource id #29
                                        )

                                    [handle:protected] => 95658e67f1a32ceb-0000000000000002
                                )

                        )

                )

            [2] => Array
                (
                    [file] => /usr/share/nginx/html/endpoints/lib/vboxconnector.php
                    [line] => 951
                    [function] => remote_machineGetDetails
                    [class] => vboxconnector
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [vm] => 98e0e6a3-1eb8-4ae1-b821-92443801f590
                                )

                        )

                )

            [3] => Array
                (
                    [file] => /usr/share/nginx/html/endpoints/api.php
                    [line] => 316
                    [function] => __call
                    [class] => vboxconnector
                    [type] => ->
                    [args] => Array
                        (
                            [0] => machineGetDetails
                            [1] => Array
                                (
                                    [0] => Array
                                        (
                                            [vm] => 98e0e6a3-1eb8-4ae1-b821-92443801f590
                                        )

                                    [1] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [data] => Array
                                                        (
                                                            [responseData] => Array
                                                                (
                                                                )

                                                        )

                                                    [errors] => Array
                                                        (
                                                        )

                                                    [persist] => Array
                                                        (
                                                        )

                                                    [messages] => Array
                                                        (
                                                        )

                                                )

                                        )

                                )

                        )

                )

            [4] => Array
                (
                    [file] => /usr/share/nginx/html/endpoints/api.php
                    [line] => 316
                    [function] => machineGetDetails
                    [class] => vboxconnector
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [vm] => 98e0e6a3-1eb8-4ae1-b821-92443801f590
                                )

                            [1] => Array
                                (
                                    [0] => Array
                                        (
                                            [data] => Array
                                                (
                                                    [responseData] => Array
                                                        (
                                                        )

                                                )

                                            [errors] => Array
                                                (
                                                )

                                            [persist] => Array
                                                (
                                                )

                                            [messages] => Array
                                                (
                                                )

                                        )

                                )

                        )

                )

        )

    [previous:Exception:private] => 
)

```

**Comment by chotaire** [comment]
Fixed in #187 (22372bf).

**Pull request merged**
