### PR TITLE
Add constructor to phpVBoxConfig class.

### PR DESCRIPTION
**Pull request by trasherdk**
Set vrdeaddress to webserver ip-address.

This is from my [6.0.x](https://github.com/trasherdk/phpvirtualbox/tree/upgrade-v6.0.10) branch
in response to [@blackcrack](https://github.com/phpvirtualbox/phpvirtualbox/issues/174#issuecomment-774958919)

### CODE REVIEW

**Comment by h6w** [comment]
Thanks.  I'll investigate this.  I'm very resistant to putting functions into config files (mainly because they're too prone to user error, as we see so frequently in the issues list).  Surely there's a better place for it.

**Comment by blackcrack** [comment]
@h6w maybe could it good, if create an own functions.php for extra functions ?
(inclusive extra functions who be added by more higher vbox-versions to support this higher versions too.
Also in the eye with sections for special functions and added versions functions.
therewith is a functions-file existent and able to add functions() with arrays adjustment's and other who is able to check out over a version() function what for a VBox version is installed and versions related functions (and able to add functions in this file for more new added functions supported able to call and able to easy updating in this file for more higher and new VBox versions )

therewith i please officially for adding a functions.php in this Web-app Repository
therewith it is also possible for move this functions in this functions.php and make open an place for such functions.

best :)

**Comment by h6w** [comment]
Higher Virtualbox Versions is conflating this issue with the need for these functions in particular.  I'd be more inclined to have a config switch which enabled these functions and/or a function that detected when they are necessary (and need no change to config at all).

**Comment by blackcrack** [comment]
exactly this, in this functions.php, there all see and know there be functions and can read and search the whole functions in exactly this file, later it's maybe a possibility to include() functions in a functions-folder as own name file like :  

**functions.php:**
```php
<?PHP
include('./functions/specialyname.php')
include('./functions/spezialyname1.php')
include('./functions/specialyname2.php')
include('./functions/specialyname3.php')
?>
```
therewith it is possible for outsorce the extra php-funtions and it is more easy to editing and updating also to add a new versions support from Virtualbox releated version in php :)

**Comment by h6w** [comment]
You're still conflating the issue of multiple versions with this PR which is about functions needed in a config setting.  These are not the same issue.

**Comment by blackcrack** [comment]
right, because i have make open an own issue :) \*head nod*

**Comment by ams-tschoening** [comment]
I really question if this should be merged.

First, a manually set IP of `127.0.0.1` should NOT be changed. Why do you think you know better than the admin setting that value explicitly and knowing best about its firewall rules, forwardings and stuff like that? It's not even the default value.

Second, how does this work if hosts provide multiple different network interfaces for multiple different purposes? phpVirtualBox alone might be accessed by different of those interfaces for various reasons already. This means the internal setting might be arbitrary different all the time, resulting in possibly difficult to debug connection problems. It's easier to force admins to configure the one correct value than to have something which works only sometimes, if at all. My phpVirtualBox e.g. is publicly available, secured by the web server for various historical reasons, but everything else of VBOX like RDP is only available via a private OVPN on the server.

Third, what's the purpose of the session handling and storing user credentials at all? There's no explanation what this has to do with changing the IP address automatically, why it's necessary etc.

Fourth, you don't even know how to handle such code properly at all currently, so simply don't by not merging. Just look at the context where it comes from: Some arbitrary RDP-client related setup problem, without further investigation of the setup etc. The RDP-IPs can be set in the web-UI already as well, not sure why this special setting was necessary that way for [that one user](https://github.com/phpvirtualbox/phpvirtualbox/issues/174#issuecomment-773779654).

**Comment by trasherdk** [comment]
@ams-tschoening It's an answer to a question, where I show how I have solved this.

Counting the number of questions regarding this topic, I'd say "admins" a having a hard time with this.

**Pull request closed without merging**
