### PR TITLE
Update de.xml

### PR DESCRIPTION
**Pull request by arthurfreycobraag**
Found wrong/inacurate translation.

### CODE REVIEW

**Comment by chotaire** [comment]
Nice find, small suggestion up for discussion: I would assume that a network adapter which is down is either "Offline", "nicht in Betrieb" or "Nicht verbunden", not "Deaktiviert". In contrast it would probably be "Online", "in Betrieb" or "Verbunden", not "Aktiviert". Deaktiviert/Aktiviert would suggest that someone has intentionally disabled the network adapter (instead of having no link or no valid configuration) which likely results in the case that the host adapter is no longer even displayed within phpVirtualBox? Please advise.

**Comment by arthurfreycobraag** [comment]
Yes, Offline or Online would work as well. It seems like we can't differenciate between "Deactivated" -> manual input and Offline -> no connection?

In that case Offline and Online would make the most sense.

**Comment by chotaire** [comment]
@h6w This should be merged. I was also totally confused by that translation.

**Comment by h6w** [comment]
Excellent.  Thanks people! :-)

**Pull request merged**
