### PR TITLE
Add Nested Virtualization & fix VRAMSize attribute missing error

### PR DESCRIPTION
**Pull request by chotaire**
This pull request adds the option to select Nested Virtualization if supported by the CPU. This will allow hypervisors to be run inside hypervisors which is very helpful for QA and testing setups.

Coded by @pasha1st - his pull request https://github.com/phpvirtualbox/phpvirtualbox/pull/167 got legitimately rejected due to several issues so I am lending a helping hand and split this into multiple pull requests. This needs tested and finally merged, we need to move forward.

### CODE REVIEW

**Comment by chotaire** [comment]
I've tested that phpvirtualbox does properly write and remove this setting from the VM config. I am unable to test if this feature actually works because it is currently only supported on AMD CPUs, which I don't have. See https://forums.virtualbox.org/viewtopic.php?f=1&t=90831 for more info about limitations with Nested Virtualization on VirtualBox. The actual commits look proper to me and I guess this can be merged.

**Comment by ZIM555** [comment]
Tested on AMD Phenom 9650. This function working

**Comment by chotaire** [comment]
@ZIM555 thank you for testing. @h6w anything else needs done before merge?

**Comment by KrakenTyio** [comment]
Nested VM are supported also for Intel in VBox 6.1

**Comment by h6w** [comment]
Sorry for the delay.  Excellent work @chotaire .  Thanks for bringing the good stuff in from @pasha1st's work. :-)

**Comment by chotaire** [comment]
a) I merged current vboxconnector.php https://github.com/phpvirtualbox/phpvirtualbox/blob/develop/endpoints/lib/vboxconnector.php from develop branch into my PR. 
b) I merged the previously proposed nested Virtualization patches again.
c) Fixed typo reported by trasherdk (in now superceded PR #217)
d) Would still give a merge conflict on the entire file. I diffed it again, chose my new version, conflict resolved. I have actually no idea what suddenly made Github report a conflict.
e) Diffed vboxconnector.php from bc88fca again with current vboxconnector.php from develop branch, looks like proper changes to me.

vboxconnector php compare

If preferred, I can delete and create a new PR, should only take a few minutes.

**Comment by chotaire** [comment]
I just checked, this file is using CRLF, like all other random files I tested in endpoints/lib so this doesn't seem to be an issue that needs to be corrected. 

Testers, go ahead and see if this works. I will join you guys shortly and update to VirtualBox 6.1.

**Comment by Polve** [comment]
I installed vbox 6.1 and tried branch "develop", but when I click on my VM I get an "Attribute does not exist" error:

`
Exception Object
(
    [message:protected] => Attribute does not exist
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /usr/local/share/phpvirtualbox-git/endpoints/lib/vboxServiceWrappers.php
    [line:protected] => 56
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /usr/local/share/phpvirtualbox-git/endpoints/lib/vboxconnector.php
                    [line] => 4225
                    [function] => __get
                    [class] => VBox_ManagedObject
                    [type] => ->
                    [args] => Array
                        (
                            [0] => VRAMSize
                        )

                )

            [1] => Array
                (
                    [file] => /usr/local/share/phpvirtualbox-git/endpoints/lib/vboxconnector.php
                    [line] => 3567
                    [function] => _machineGetDetails
                    [class] => vboxconnector
                    [type] => ->
                    [args] => Array
                        (
                            [0] => IMachine Object
                                (
                                    [connection:protected] => SoapClient Object
                                        (
                                            [location] => http://127.0.0.1:18083/
                                            [_features] => 5
                                            [_connection_timeout] => 20
                                            [_stream_context] => Resource id #5
                                            [_soap_version] => 1
                                            [sdl] => Resource id #6
                                            [httpsocket] => Resource id #7
                                            [_use_proxy] => 0
                                            [httpurl] => Resource id #23
                                        )

                                    [handle:protected] => b826cfc00a473451-0000000000000002
                                )

                        )

                )

            [2] => Array
                (
                    [file] => /usr/local/share/phpvirtualbox-git/endpoints/lib/vboxconnector.php
                    [line] => 951
                    [function] => remote_machineGetDetails
                    [class] => vboxconnector
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [vm] => 67052513-29c0-4e15-815b-a7692cac84b4
                                )

                        )

                )

            [3] => Array
                (
                    [file] => /usr/local/share/phpvirtualbox-git/endpoints/api.php
                    [line] => 316
                    [function] => __call
                    [class] => vboxconnector
                    [type] => ->
                    [args] => Array
                        (
                            [0] => machineGetDetails
                            [1] => Array
                                (
                                    [0] => Array
                                        (
                                            [vm] => 67052513-29c0-4e15-815b-a7692cac84b4
                                        )

                                    [1] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [data] => Array
                                                        (
                                                            [responseData] => Array
                                                                (
                                                                )

                                                        )

                                                    [errors] => Array
                                                        (
                                                        )

                                                    [persist] => Array
                                                        (
                                                        )

                                                    [messages] => Array
                                                        (
                                                        )

                                                )

                                        )

                                )

                        )

                )

        )

    [previous:Exception:private] => 
)
`

**Comment by chotaire** [comment]
@Polve Yep it is caused by a different PR. I am currently working on a fix.

**Comment by chotaire** [comment]
@Polve Please try the supplied fix. Thanks @cesium147 for the VirtualBox-6.1 patch.

**Comment by chotaire** [comment]
After upgrading to VirtualBox 6.1, I've tried pretty much all features, creating, editing, deleting VMs and playing with most configuration parameters, creating, restoring, merging, deleting snapshots, changing VGA adapters (haven't tested if they actually work), setting Nested Virtualization feature on/off. From what I can see, everything works like a charme. This is awesome.

The only feature I haven't tried is Shared Folders. 

@h6w Please review with most urgent priority as it fixes an issue that all VirtualBox 6.1 users will experience on current develop branch (exception when simply clicking a VM).

**Comment by Polve** [comment]
> @Polve Please try the supplied fix
It works fine for me, thanks!

**Comment by h6w** [comment]
Ok, so we're going back to the $m->GraphicsAdapter model.  I must admit that raised an eyebrow when it was changed the first time.  This seems a more sensible model.  Thanks! :-)

**Comment by chotaire** [comment]
@h6w thanks for the quick action. I hope this will give developers a good base to work with in the future as we now have a really well working 6.1 version. I've tested it a lot today and decided to move it to production, it works so much better than master branch. 

VirtualBox 5.2 goes out of support in July 2020. I hope you can keep an eye on this and merge develop to master in time. That would also stop confusing users wondering why there is no support for 6.0 and 6.1. 

All eyes on @pasha1st and @cesium147 who made this huge step forward possible. ♥

**Comment by h6w** [comment]
Yep.  Let's give it 14 days to settle in and then I'll release if there aren't any more reports of major issues. :-)

**Comment by chotaire** [comment]
The VirtualBox dev team in Germany being thankful for the news is sure "that it will make people happy".

**Pull request merged**
