### PR TITLE
VirtualBox 6.0.x adaptation

### PR DESCRIPTION
**Pull request by pasha1st**
VirtualBox 6.0.x adoptation with major VB6 features support
Please note README and About changes when merge

### CODE REVIEW

**Comment by Pheromon** [comment]
Nice! Please merge :-)

**Comment by h6w** [comment]
I'm afraid I can't accept pull requests that change the project URL and imply a non-phpvirtualbox group "adaptation".  There are more changes here than a simple version upgrade, please break your merge request into sections to make the commit clearer.  Thanks.

**Comment by pasha1st** [comment]
Now I cleared url changes and other copyright canges
Changes:
1. updated *.wdsl - from VBox 6.0.6 SDK
2. changed vboxconnector.php for new options
3. updated phpvirtualbox.js for new options* and some informational boxes. Also changed max SCSI ports to 15 as manual states. USB storage block reformatted.

New options:
System: Nested VT-x/AMD-V option (if supported by system)
Display: graphics controller select (VBoxVGS/VMSVGA/VboxSVGA)
Storage: NVMe controller type support
Storage: TRIM option for VDI disk images

It is hard to split all changes, and it is much more then "simple version upgrade"

**Comment by h6w** [comment]
Yes, but the title of the push is "6.0.6 adaptation" which is what we expect to see.

As much as we value your contribution, you have to understand from our point of view.  Bundling feature changes together is bad because:
(a) We can't tell which change applies to what
(b) We can't roll back an individual feature change cleanly
(c) It becomes unclear what we're accepting
(d) Security issues creep in because each change can't be tested in isolation

phpvirtualbox is software which is rolled out to 1000s of machines each day and is frequently available publicly.  As much as we value your contribution, we have to follow some processes to make all changes clear and understandable to everyone.

**Comment by h6w** [comment]
One other note.  Please don't edit the changelog.  That's for us to do at release time.

**Comment by meiser79** [comment]
Could you maybe fix the RDP settings tab? I can't switch to this tab and edit the settings. Many thanks!

**Comment by meiser79** [comment]
Could you maybe fix the RDP settings tab? I can't switch to this tab and edit the settings. Many thanks!

BTW, there's a small typo "Extended Features**1**" so that the translation doesn't work.

**Comment by trasherdk** [comment]
Me, personally, would like to see @pasha1st contributions get into this repository.
But, I agree, PR's have to be structured, specific and clean, to allow for review by other users.
I'm on 6.0.{4,6}, having no serious issues.

**Comment by martijintro** [comment]
"Could you maybe fix the RDP settings tab? I can't switch to this tab and edit the settings. Many thanks!"

That means you can't see the VM screens with that flash technology?

**Comment by meiser79** [comment]
Last time I checked, I couldn't configure the remote display settings as it was greyed out. I just checked again to make a screenshot, but it's now available. Sorry for the noise.

**Comment by jmar83** [comment]
OK, so you said now it works. Will try it, thank you very much!! ;-)

**Comment by martijintro** [comment]
where can i download it, was it (vb 6.0.x compatibilty feature) added to the master branch?

**Comment by martijintro** [comment]
yes, current dev branch seems to work with vb 6.0.x in general.

important: don't forget to activate remote display pm port 9000-9100 if you used the windows vb gui for your vm before you used phpvirtualbox!

**Comment by martijintro** [comment]
but: why the remote screen always goes to 127.0.0.1? why is there no function like "getHostIPAddress" or something like that on php code?!?!

That made a big mess, because i used a remote ip for phpvirtualbox and then the remote screen used 127.0.0.1 - and on my local pc, 127.0.0.1, was the same phpvirtualbox installation too - very confusing!!!!!!!!!!!

**Comment by flyqieqq** [comment]
Hope to see the merge, which adds a lot of features support :)

**Comment by trasherdk** [comment]
Can someone please, marge or close this one?  
Are there any issues that need addressing?  
If yes, which?

**Comment by h6w** [comment]
The issues have been made clear above.  So I'm closing it.

**Pull request closed without merging**
