### PR TITLE
Czech localization

### PR DESCRIPTION
**Pull request by p-bo**
Hi,
followed instructions in
https://github.com/phpvirtualbox/phpvirtualbox/blob/develop/languages/languages.txt

### CODE REVIEW

**Comment by h6w** [comment]
That's excellent.  Thanks!

Loooove Czech Republic, by the way!  Have had a lot of fun there. :-D

**Comment by tom077** [comment]
Hi,
Love Czech Republic too, but this new translation does not seem to translate the GUI.
Does it work well for you @p-bo ?

The "cs.dat" committed file is a html copy of a github web page.

**Comment by p-bo** [comment]
@tom077, @h6w thanks for catching it, my fault - did stupid mistake during downloading parse_vbox_lang.php (btw in instructions in https://github.com/phpvirtualbox/phpvirtualbox/blob/develop/languages/languages.txt is typo - pasre instead of parse) didn't downloaded raw but preview from github and php command was quite happy to send it to output file then.
Corrected, but now i have problem parse_vbox_lang.php probably not compatible with php7:

PHP Notice:  Undefined index: TS in parse_vbox_lang.php on line 23
PHP Warning:  Invalid argument supplied for foreach() in parse_vbox_lang.php on line 23

So, would it be possible to correct it or generate cs.dat if you have compatible php version at your disposition?

Source ts is https://www.virtualbox.org/browser/vbox/trunk#src/VBox/Frontends/VirtualBox/nls/qt_cs.ts

Thanks :)

**Comment by tom077** [comment]
Hi,
The "parse_vbox_lang.php" works well for me with php7. Actually, I think we need to use it with "VirtualBox_cs.ts" from the virtualbox sources, not "qt_cs.ts".
I made a PR with a new "cs.dat" which seems to work well.
Could you check the GUI translation? It looks like Czech, but I'm not sure, I don't speak Czech :)

**Pull request merged**
