### PR TITLE
Improve error handling at startup

### PR DESCRIPTION
**Pull request by tom077**
- Check config.php and produce a specific error message in case of syntax error.
- Check PHP extension requirements and produce a specific error message if SOAP or JSON extensions are not enabled.
- Produce a generic error if none of the error above

### CODE REVIEW

**Comment by tom077** [comment]
At startup, phpvirtualbox can produce the same error message for different reasons.
For example, If we forgot to enable soap PHP extensions, we get a message saying that the most common error is a syntax error in config.php.

A lot of bug reports are related to error messages that are not specific enough.

**Comment by h6w** [comment]
This is a great idea, but I think that it needs to be placed in a more secure location.  By creating publicly-accessible PHP files not behind the authentication, we would be providing a wider attack surface for many different kinds of attacks.  It would also create ways to make it easier to identify where and what versions of this software is installed.  I think we should perhaps shift this into a subfolder that is inaccessible by default (e.g. .utils) and then have the user copy them if needed, or we should make this code run as a check while the software is initialising and give feedback iff the tests fail for some reason.

**Comment by tom077** [comment]
Ok it's better not to increase the vulnerability of the app.

But, there are already some files in the "endpoints" folder that are publicly-accessible PHP files not behind the authentication: language.php, rdp.php, ..

Even the api.php file can be used without any authentication. Anyone can try to connect to our vboxwebsrv with a simple curl command. It's also a huge vulnerability.

**Comment by h6w** [comment]
I agree, and I didn't realise it until I saw you add more of them.  I'll make those a separate issue.

**Pull request closed without merging**
