### PR TITLE
PHP8.2 compatibility + VirtualBox 7.0

### PR DESCRIPTION
**Pull request by BartekSz95**
Like on title, this version is compatible with PHP 8.1. Works great on my server.

### CODE REVIEW

**Comment by BartekSz95** [comment]
I added Windows 11 icon + fix for Windows 10 icon

**Comment by gh-tek** [comment]
Tested and started using this with Ubuntu 22.04.1 LTS with PHP 8.1.

**Review by zoon01 — CHANGES_REQUESTED** [review]
you made not proper fix for os win 10 64 bits

please adjust to:

		case "Windows10":       strIcon = "os_win10.png"; break;
		case "Windows10_64":    strIcon = "os_win10_64.png"; break;
		case "Windows11_64":    strIcon = "os_win11_64.png"; break;

where is non 64 bits os 11 icon?

**Comment by BartekSz95** [comment]
I see only on MS download page Win 11 64 bit.

**Comment by BartekSz95** [comment]
I added compatibility for VBox version 7.0. I don't know that any others things need to be fixed, because I didn't test this on production yet. I still use VBox 6.1 on my dedicated server with VM's. But I will change this in incoming few days :)

**Comment by Neustradamus** [comment]
@BartekSz95: Can you reopen your PR?
I would like to merge the code to have a VirtualBox 7.0 which works.

Thanks in advance.

**Pull request closed without merging**
