### PR TITLE
Virtualbox 5.2

### PR DESCRIPTION
**Pull request by Kunzol**
Update of WSDL files from virtualbox-5.2 source

### CODE REVIEW

**Comment by h6w** [comment]
How is this different from PR #66 ?

**Comment by Kunzol** [comment]
I guess the only difference is that in this PR the wsdl-files are explicitly generated from the source-tree of Virtualbox-5.2 and added as files. Which makes it easy to use.

**Comment by h6w** [comment]
The PR doesn't show there being a difference between wsdl files at all.  There are only 3 files and 11 lines changed from the current files in the develop branch.  That's why I was asking.  I see 3 changes:

1. A change in the text in README.md
2. A change in the theme
3. A change in PHPVBOX_VER.

**Comment by Kunzol** [comment]
Actually I wanted to make the PR for ezraholm50/phpvirtualbox, because this looked like it was dead.
I don't know, why this PR is shown in the original, not in the fork. It seems that this PR contains all patches from that fork. If I knew, how to "undo" this, I would do it, and try it again.
Git seems to complex for me. I should go back to SVN.

**Comment by h6w** [comment]
You need to be on the branch linked to ezraholm50 if you want to push a PR to there.  `git set remote-url` or some such IIRC.

I'll close this for you.  

Cheers, 
Tudor.

**Comment by Neustradamus** [comment]
Can you confirm if the latest 5.2.x (EOL): https://www.virtualbox.org/wiki/Changelog-5.2: VirtualBox 5.2.44 (released July 14 2020)?
- https://github.com/phpvirtualbox/phpvirtualbox/tree/master

**Pull request closed without merging**
